apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connect
  template:
    metadata:
      labels:
        app: debezium-connect
    spec:
      containers:
      - name: connect
        image: quay.io/debezium/connect:2.4
        ports:
        - containerPort: 8083
        env:
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value: "my_connect_configs"
        - name: OFFSET_STORAGE_TOPIC
          value: "my_connect_offsets"
        - name: STATUS_STORAGE_TOPIC
          value: "my_connect_statuses"
        - name: BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: DATABASE_HOST
          value: "mysql-service"

---
apiVersion: v1
kind: Service
metadata:
  name: debezium-connect-service
spec:
  selector:
    app: debezium-connect
  ports:
    - name: connect-port
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
